version: '3.8'
services:
  api:
    build: .
    container_name: my-fastapi-container
    restart: always
    ports:
      - "8008:8000"
    # Đây là chỗ nạp file env
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000